name: tunnel_controller
description: Cloudflare Tunnel Controller
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.0
  permission_handler: ^11.0.0
  device_info_ce: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cloudflared
    - assets/proot
    - assets/proot_loader
    - assets/libtalloc.so.2 
